name: aff-ai
root: ~/Affirm/ai_assistant

on_project_start: printf '\033]0;mux aff-ai\007'

windows:
  - editor:
      layout: main-vertical
      panes:
        - tmux resize-pane -x 150 && vim
        - claude
