name: att
root: ~/Affirm/all-the-things

on_project_start: printf '\033]0;mux att\007'

windows:
  - editor:
      layout: main-vertical
      panes:
        - tmux resize-pane -x 140 && vim
        -
  - claude: claude
  - tests:
  - docker:
